name: CI
on: push
  jobs:
    run_tests:
     runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js Environment
      uses: actions/setup-node@v3

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm test

  run_lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js Environment
      uses: actions/setup-node@v3

    - name: Install Dependencies
      run: npm ci

    - name: Run Linter
      run: npx eslint .

    - name: Test & publish code coverage
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v3.0.0
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true